# Generated by Django 6.0 on 2026-01-03 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
