# Generated by Django 6.0 on 2026-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_marinewastedetection_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='analysis_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marinewastedetection',
            name='sampling_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
