# Generated by Django 6.0 on 2026-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_marinewastedetection_analysis_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='ecological_risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marinewastedetection',
            name='ecological_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
