# Generated by Django 6.0 on 2026-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marinewastedetection_ecological_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='aggregated_hazard_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marinewastedetection',
            name='hazard_analytics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
