# Generated by Django 6.0 on 2026-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_marinewastedetection_aggregated_hazard_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='scientific_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
