# Generated by Django 6.0 on 2026-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_marinewastedetection_scientific_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinewastedetection',
            name='beach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
